### ISSUE TITLE
Too much space around text in syntax diagram in PDF; same diagram in HTML5 output (SVG) looks okay

### ISSUE THREAD

**Issue by GrahamHannington** [robander/svg-syntaxdiagrams#18]
Screenshot from a PDF:

![dita-ot-syntaxdiagram-pdf-extraneous-space](https://user-images.githubusercontent.com/8519708/90253369-9fb0f080-de73-11ea-9d40-bd6450024c30.png)

Screenshot of corresponding SVG file (from HTML5 output) presented in Chrome:

![dita-ot-syntaxdiagram-svg-from-html5-output](https://user-images.githubusercontent.com/8519708/90253440-bce5bf00-de73-11ea-8f7d-e4f9d39a8f0b.png)

Same DITA input. I'm just switching `--format=pdf` to `--format=html5`.

In PDF, text in diagrams has too much space around it.

It's as if the PDF processing is "expecting" a larger font. Acrobat reports the text in the PDF as 8pt; the CSS in the SVG file created for HTML5 output specifies 8pt.

I've tried experimenting with the `font-family` in `plugins/com.moldflow.dita.syntaxdiagram2svg/xsl/syntaxdiagram2svg.xsl`, but to no avail so far.

Am I doing something wrong?

**Comment by GrahamHannington** [comment]
If I take a syntax diagram SVG file (that looks fine when opened in a web browser) that was generated using the HTML5 output, and I refer to that SVG file in an `<image>` element in a DITA topic, and then I format that DITA topic to PDF, then the diagram in the resulting PDF exhibits the same problem as a `<syntaxdiagram>` rendered directly to PDF: too much space around the text.

**Comment by robander** [comment]
The actual width of the text box is determined by a JavaScript interpreter (run from Batik), which gives different results based on the fonts that it finds on your system + the fonts listed in the diagram file. I remember that it tends to give too much space for some cases, but removing that space meant some other text boxes gave too little, which could not be allowed.

The last time I looked at this code it was set up to render HTML versions inline (not referencing the files), so it's also possible that the HTML version is picking up the font from the HTML page itself, while PDF is using some other default.

Beyond that, I'm not really able to help -- this is one of the harder to work with parts of the code, and I know at different times we got different PDF results from seemingly identical servers (but which turned out to have a slightly different set of system fonts installed).
